# Setup
title: 'Notes'
baseurl: /notes

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  show_warnings: true
highlighter: rouge
permalink: :title:output_ext
future: true
timezone: Australia/Melbourne

#collections_dir: notebooks
collections:
  notebooks:
    output: true

# Excludes
excludes:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor

plugins:
  - jekyll-relative-links

# https://github.com/benbalter/jekyll-relative-links
relative_links:
  enabled: true
  collectoins: true