name: make-pdfs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Makefile
        uses: jsinkers/md-to-pdf@master
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot] "
          git config --local user.name "GitHub Action"
          git checkout -b pdf
          git add static/pdf
          git diff-index --quiet HEAD || git commit -m ":wave: Here are the pdf files for the latest notes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
